- name: Check if directory exists
  stat:
    path: ~/fonts
  register: dir_check
  tags:
    - font

- name: Create fonts dir
  shell: mkdir ~/fonts
  when: not dir_check.stat.exists
  tags:
    - font

- name: Install meslo lg font Regular
  shell: cd $HOME/fonts && curl -L -o MesloLGS_NF_Regular https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf
  tags:
    - font

- name: Install meslo lg font Bold
  shell: cd $HOME/fonts && curl -L -o MesloLGS_NF_Bold https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold.ttf
  tags:
    - font

- name: Install meslo lg font Italic
  shell: cd $HOME/fonts && curl -L -o MesloLGS_NF_Italic https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Italic.ttf
  tags:
    - font

- name: Install meslo lg font Bold Italic
  shell: cd $HOME/fonts && curl -L -o MesloLGS_NF_Bold_Italic https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Bold%20Italic.ttf
  tags:
    - font
