- name: Git personal setup email
  git_config:
    name: user.email
    scope: global
    value: "wye139629@gamil.com"
  tags:
    - git-personal
- name: Git personal setup name
  git_config:
    name: user.name
    scope: global
    value: "William Liu"
  tags:
    - git-personal
