- name: Install nvm
  shell: curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.3/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
  tags:
    - node

- name: Add snippet to ~/.bashrc file
  lineinfile:
    path: ~/.bashrc
    line: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm
    insertafter: EOF
    state: present
  tags:
    - node

- name: Install node 14.20 version
  shell: |
    export NVM_DIR="$HOME/.nvm"
    . "$NVM_DIR/nvm.sh"
    nvm install 14.20 && nvm install 16.16 && nvm alias default 16.16
  tags:
    - node
