- name: Ensure .ssh directory exists.
  file:
    dest: "{{ dest_key | dirname }}"
    state: directory
    mode: "0700" # Owner has read, write, and execute permissions
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key
  copy:
    src: "{{ source_key }}"
    dest: "{{ dest_key }}"
    mode: "0600" # Owner has read and write permissions
  tags:
    - dotfiles
    - install
    - ssh
- name: Install ssh key public
  copy:
    src: "{{ source_key }}.pub"
    dest: "{{ dest_key }}.pub"
    mode: "0644" # Everyone has read access
  tags:
    - dotfiles
    - install
    - ssh
- name: Set authorized key taken from file
  authorized_key:
    user: william
    state: present
    key: "{{ lookup('file', lookup('env', 'HOME') + '/.ssh/id_rsa.pub') }}"
  with_fileglob:
    - "{{ lookup('env', 'HOME') }}/.ssh/*.pub"
