- name: Install zsh
  homebrew: name=zsh
  when:
    - ansible_distribution == 'Ubuntu'
  tags:
    - zsh
- name: Change shell
  become: true
  command: chsh -s /usr/local/bin/zsh "william"
  when:
    - ansible_distribution == 'Ubuntu'
  tags:
    - zsh
- name: Install oh-my-zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  tags:
    - zsh
- name: Install zsh autosuggestion plugin
  ansible.builtin.git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions.git"
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags:
    - zsh
- name: Install powerlevel10k theme
  ansible.builtin.git:
    depth: 1
    repo: "https://github.com/romkatv/powerlevel10k.git"
    dest: "~/.oh-my-zsh/themes/powerlevel10k"
  tags:
    - zsh
